apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rain
  template:
    metadata:
      labels:
        app: rain
    spec:
      containers:
      - name: rain
        image: asia-south1-docker.pkg.dev/PROJECT_ID_PLACEHOLDER/rain-prediction/rain:TAG_PLACEHOLDER
        ports:
        - containerPort: 5000
        # Resource limits and health checks
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Liveness and readiness probes
        livenessProbe:
          httpGet:
            path: /health  
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health  
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: rain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer