name: CI/CD Deployment to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: "rain"
  GKE_REGION: "asia-south1"
  DEPLOYMENT_NAME: "rain"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    container:
      image: google/cloud-sdk:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure GCloud and Docker
        run: |
          gcloud config set project "$PROJECT_ID"
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${PROJECT_ID}/rain-prediction/rain:${GITHUB_SHA}"
          
          echo "Building image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          
          echo "Pushing image: $IMAGE_NAME"
          docker push $IMAGE_NAME
          
          echo "IMAGE=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" \
            --region "$GKE_REGION" \
            --project "$PROJECT_ID"

      - name: Deploy to GKE
        run: |
          # Replace placeholders in kubernetes deployment
          sed -i "s/PROJECT_ID_PLACEHOLDER/$PROJECT_ID/g" kubernetes-deployment.yaml
          sed -i "s/TAG_PLACEHOLDER/$GITHUB_SHA/g" kubernetes-deployment.yaml
          
          # Show the updated deployment file for debugging
          echo "Updated kubernetes-deployment.yaml:"
          
          grep "image:" kubernetes-deployment.yaml
          
          kubectl apply -f kubernetes-deployment.yaml